### ISSUE TITLE
EF Core select all columns in SQL when a DTO mapper is called on Select()

### ISSUE THREAD

**Issue by MrDave1999** [DentallApp/back-end#6]
The following LINQ:
https://github.com/DentallApp/back-end/blob/9a939087a8a8743bb0cd593573bda42c96119475/src/Features/Users/UserRepository.cs#L28-L38
EF Core translates it to:
```sql
SELECT `u`.`id` AS `UserId`, `u`.`username` AS `UserName`, `p`.`names` AS `Name`, `u`.`password` AS `Password`
FROM `users` AS `u`
INNER JOIN `persons` AS `p` ON `u`.`person_id` = `p`.`id`
WHERE `u`.`username` = @__username_0
LIMIT 1
```
In this case EF Core selects the columns associated to `UserResetPasswordDto`.

But when the mapper is called in the `Select` method:
```cs
.Select(user => user.MapToUserResetPasswordDto()) 
```
EF Core translates it to:
```sql
SELECT `u`.`id`, `u`.`created_at`, `u`.`password`, `u`.`person_id`, `u`.`refresh_token`, `u`.`refresh_token_expiry`, `u`.`updated_at`, `u`.`username`, `p`.`id`, `p`.`cell_phone`, `p`.`created_at`, `p`.`date_birth`, `p`.`document`, `p`.`email`, `p`.`gender_id`, `p`.`last_names`, `p`.`names`, `p`.`updated_at`
FROM `users` AS `u`
INNER JOIN `persons` AS `p` ON `u`.`person_id` = `p`.`id`
WHERE `u`.`username` = @__username_0
LIMIT 1
```
EF Core selects ALL columns. The mapper code is:
https://github.com/DentallApp/back-end/blob/9a939087a8a8743bb0cd593573bda42c96119475/src/Features/Users/UserMapper.cs#L64-L71

There is a possible solution in this StackOverflow answer: https://stackoverflow.com/a/62138200 (must be tested)

This problem is also mentioned here: https://github.com/dotnet/efcore/issues/24509

**Comment by MrDave1999** [comment]
I have published a [NuGet package](https://www.nuget.org/packages/EFCore.CustomQueryPreprocessor/) with the solution proposed by Ivan Stoev (see https://stackoverflow.com/a/62138200).

**Comment by DevD4v3** [comment]
In EF Core 7.0 added [Interception to modify the LINQ expression tree](https://github.com/dotnet/efcore/issues/28505), so the custom code should be simpler:
```cs
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.EntityFrameworkCore.Diagnostics;

namespace Microsoft.EntityFrameworkCore
{
    public static class DelegateDecompilerDbContextOptionsBuilderExtensions
    {
        public static DbContextOptionsBuilder AddDelegateDecompiler(this DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder.AddInterceptors(new DelegateDecompilerQueryPreprocessor());
    }
}

namespace Microsoft.EntityFrameworkCore.Query
{
    using System.Linq.Expressions;
    using DelegateDecompiler;
    public class DelegateDecompilerQueryPreprocessor : IQueryExpressionInterceptor
    {
        Expression IQueryExpressionInterceptor.QueryCompilationStarting(Expression queryExpression, QueryExpressionEventData eventData)
            => DecompileExpressionVisitor.Decompile(queryExpression);
    }
}
```
**Reference:** https://stackoverflow.com/a/62138200.
